# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hitchcabs' do

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD'
    pod 'CountryPickerSwift'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'SideMenu'
    pod 'TPKeyboardAvoiding'

    pod 'UberRides', '~> 0.7'
    pod 'LyftSDK'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hitchcabs

end
